version: "3.1"
services:
    webserver:
      image: nginx:alpine
      container_name: ngnix-prueba
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./docker/nginx/sites:/etc/nginx/sites-available
      ports:
       - "8082:82"

    php-fpm:
      build: docker/php-fpm
      container_name: php-prueba
      working_dir: /application
      volumes:
        - ./prueba:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini


    appserver:
      image: 'angular_prueba'
      container_name: angular_prueba_cont
      # Build the image if don't exist
      build: './frontend' 
  


